typography_spectrum: 0.5379635969261722
color:
  brandStrength: 0.09696743532120812
  lightness: 0.5968540457673002
  saturation: 0.42529547144963153
  rhythmicContrast: 0.3723506440148495
  brandColors:
    - '#962D3E'
    - '#343642'
    - '#979C9C'
    - '#F2EBC7'
    - '#348899'
github: true
opengraph:
  appId: 'https://www.facebook.com/voicesofamerikua'
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/d08a2b83-8399-4e30-832a-8319ea8c0804.jpg
layout_spectrum: 0.7896398731924151
logo: null
name: Voices of Amerikua
navigation:
  - name: Media
    id: 2df895e4-9bab-42b7-b439-41e38d77df42
    type: content
  - name: Support us
    id: aa1d866f-f80b-4b08-8036-2efbab3a96ba
    type: content
  - name: About/ Acerca de
    id: a7ef9d05-3142-4286-94dd-1b99ff306c56
    type: content
  - name: Facebook
    url: 'https://www.facebook.com/voicesofamerikua/?fref=ts'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/31e94d5d-e9f4-455f-80f0-aadd7ddef50d.jpg
title: Voices of Amerikua
content: []
description: Indigenous media alliance and documentary series
purpose:
  - type: internal
    label: Support
    item: aa1d866f-f80b-4b08-8036-2efbab3a96ba
