layout_spectrum: 0.3165367131587118
typography_spectrum: 0.5852756018284708
color:
  brandStrength: 0.4569888550322503
  lightness: 0.6091126501560211
  saturation: 0.20489230751991272
  rhythmicContrast: 0.14967030193656683
  brandColors:
    - '#962D3E'
    - '#343642'
    - '#979C9C'
    - '#F2EBC7'
    - '#348899'
github: true
opengraph:
  appId: 'https://www.facebook.com/voicesofamerikua'
logo: null
name: Voices of Amerikua
navigation:
  - name: About/ Acerca de
    id: a7ef9d05-3142-4286-94dd-1b99ff306c56
    type: content
  - name: Media
    id: 2df895e4-9bab-42b7-b439-41e38d77df42
    type: content
  - name: Blog
    id: 3a3ead16-47a0-44ae-9437-008ecdd785dc
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/31e94d5d-e9f4-455f-80f0-aadd7ddef50d.jpg
title: Voices of Amerikua
description: Voces de Amerikua
purpose:
  - type: contact
    url: 'mailto:voicesofamerikua@gmail.com'
    label: 'Contact us:'
