layout_spectrum: 0.8971842949768288
typography_spectrum: 0.870104550115469
color:
  brandStrength: 0.36890784054570414
  lightness: 0.16887966725173048
  saturation: 0.42480248530552084
  rhythmicContrast: 0.4656034121086065
  brandColors:
    - '#962D3E'
    - '#343642'
    - '#979C9C'
    - '#F2EBC7'
    - '#348899'
github: true
opengraph:
  appId: 'https://www.facebook.com/voicesofamerikua'
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/d08a2b83-8399-4e30-832a-8319ea8c0804.jpg
logo: null
name: Voices of Amerikua
navigation:
  - name: About/ Acerca de
    id: a7ef9d05-3142-4286-94dd-1b99ff306c56
    type: content
  - name: Support us
    id: aa1d866f-f80b-4b08-8036-2efbab3a96ba
    type: content
  - name: Media
    id: 2df895e4-9bab-42b7-b439-41e38d77df42
    type: content
  - name: Facebook
    url: 'https://www.facebook.com/voicesofamerikua/?fref=ts'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/31e94d5d-e9f4-455f-80f0-aadd7ddef50d.jpg
title: Voices of Amerikua
content: []
description: Indigenous media alliance and documentary series
purpose:
  - type: internal
    label: Support
    item: aa1d866f-f80b-4b08-8036-2efbab3a96ba
