layout_spectrum: 0.5916778862832279
typography_spectrum: 0.581566051196602
color:
  brandStrength: 0.6586557790175965
  lightness: 0.3983930441017014
  saturation: 0.8863155474196567
  rhythmicContrast: 0.9243366187860692
  brandColors:
    - '#962D3E'
    - '#343642'
    - '#979C9C'
    - '#F2EBC7'
    - '#348899'
github: true
opengraph:
  appId: 'https://www.facebook.com/voicesofamerikua'
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/d08a2b83-8399-4e30-832a-8319ea8c0804.jpg
logo: null
name: Voices of Amerikua
navigation:
  - name: About
    id: a7ef9d05-3142-4286-94dd-1b99ff306c56
    type: content
  - name: Media
    id: 2df895e4-9bab-42b7-b439-41e38d77df42
    type: content
  - name: Facebook
    url: 'https://www.facebook.com/voicesofamerikua/?fref=ts'
    type: external
  - name: Support us
    id: aa1d866f-f80b-4b08-8036-2efbab3a96ba
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/31e94d5d-e9f4-455f-80f0-aadd7ddef50d.jpg
title: Voices of Amerikua
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://s3-us-west-2.amazonaws.com/the-grid-img/p/ccd8295553eade9a33d5ef7c5070875d465e4074.jpg">
    src: >-
      https://s3-us-west-2.amazonaws.com/the-grid-img/p/ccd8295553eade9a33d5ef7c5070875d465e4074.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://s3-us-west-2.amazonaws.com'
        name: .s3-us-west-2.amazonaws.com
        favicon: null
        domain: s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: >-
  Sharing the voice of indigenous people working to protect their culture,
  territories and Mother Nature in North, Central and South America.
purpose:
  - type: internal
    label: Support
    item: aa1d866f-f80b-4b08-8036-2efbab3a96ba
  - type: internal
    label: '#LandRightsNow'
    item: 10006a8f-efc1-4545-ada2-1e4d6701a864
url: 'https://www.voicesofamerikua.net'
